### ISSUE TITLE
Internal Exception error when trying to load the server. 

### ISSUE THREAD

**Issue by BinxetyBinx** [Siphalor/bouncylife#4] opened 2019-10-06 23:46 UTC
If I'm reporting this to the wrong people I apologize but I was able to both replicate and fix this and it involved this mod both times. I'm running an AOF:Strawberry server. Wanted to add a few things that were requested. When I added BouncyLife people started not being able to connect and got the following error. 

![Untitled](https://user-images.githubusercontent.com/47510715/66277787-f10e4d80-e868-11e9-8c36-0cd1c6a28058.png)

Removing Bouncylife and restarting the server fixed the problem. Readding it and ONLY it to the modpack restarted the problems.

I added the following along with bouncylife (all were the latest versions):

Adorn
Allure
Arcane Magic
Beach Slimes
Cauldronbrew
Clothesline
Composable Automation
Demense
EggsPlus
Epicurean Gastronomy
Fabriblocks
Faeriwfire
Fishtraps
Glintcolor
Materialsation
MoEnchantments
Morepotions
Mooblooms

**Comment by Siphalor** [comment] 2019-10-27 18:14
Sorry for the really late answer but Bouncy Life is one of my projects with lower priority and since I was kinda busy IRL.

But now to the topic I tried to reproduce that issue with a local server and it didn't crash.
It would be really cool if you could give me a log file so I could figure out what exactly worked wrong.

**Comment by BinxetyBinx** [comment] 2019-10-27 20:20
I can see if I have an old log. Funnily enough I backdated a version from what I was using and everything went through fine. When there's downtime again and we don't have people on the server I can change the server files again to get you a new log if I don't have one.

**Comment by Siphalor** [comment] 2020-08-14 20:58
I'm gonna close this as outdated

**Closed as completed by Siphalor** 2020-08-14 20:58 UTC
